from __future__ import annotations

from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = REPO_ROOT / "src"
MEA_DIR = SRC_ROOT / "MEA"
REFERENCE_DATA_ROOT = REPO_ROOT / "data" / "reference"
DATA_ROOT = REFERENCE_DATA_ROOT / "MEA"
EPCSAFT_DATASET_ROOT = REFERENCE_DATA_ROOT / "epcsaft_datasets"
ANALYSES_ROOT = REPO_ROOT / "analyses"
PAPER_VALIDATION_ANALYSES = ANALYSES_ROOT / "paper_validation"
PHASE1_ANALYSES = ANALYSES_ROOT / "phase1"
PHASE2_ANALYSES = ANALYSES_ROOT / "phase2"
PHASE3_ANALYSES = ANALYSES_ROOT / "phase3"

SIX_SPECIES_ANALYSIS = PHASE1_ANALYSES / "six_species_baseline"
EPCSAFT_NEUTRAL_ANALYSIS = PHASE1_ANALYSES / "neutral_epcsaft_parity"
EPCSAFT_IONIC_ANALYSIS = PHASE3_ANALYSES / "ionic_epcsaft_regression"
BAYGI_ANALYSIS = PAPER_VALIDATION_ANALYSES / "2015_baygi"

LEGACY_BASELINE_OUT = SIX_SPECIES_ANALYSIS / "results" / "pressure"
SIX_SPECIES_PROCESSED = SIX_SPECIES_ANALYSIS / "data" / "processed"

CANONICAL_TEMPERATURE_C = 40.0
CANONICAL_TEMPERATURE_K = CANONICAL_TEMPERATURE_C + 273.15
CANONICAL_MEA_WEIGHT_FRACTION = 0.3
JOU_TEMPERATURES_C = (40, 60, 80, 100, 120)

SIX_SPECIES_ALPHA_GRID = np.linspace(0.002, 0.8, 101)
